### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by yan517**
彭彭, 我是林欣欣
http://18.181.123.151:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done, but if we try to scroll down and up quickly, your code may load the same page multiple times. Try to address and solve this issue.

**Comment by yan517** [comment]
彭彭, I have updated the code. Please check again, thank you.

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
